sudo: required #super user level permissions required
services:
    - docker

before_install:
    - docker build -t mariamjamal32/docker-react -f Dockerfile.dev .

script:
    - docker run mariamjamal32/docker-react npm run test -- --coverage
